all: lab_a5part1 lab_a5part2
		
lab_a5part1: lab_a5part1.c
		gcc lab_a5part1.c -o lab_a5part1 -ansi -Wall -pedantic
lab_a5part2: lab_a5part2.c
		gcc lab_a5part2.c -o lab_a5part2 -ansi -Wall -pedantic
clean:
		rm lab_a5part1 lab_a5part2
