all: laba6part1 laba6part2
		
laba6part1: laba6part1.c
		gcc laba6part1.c -o laba6part1 -ansi -Wall -pedantic
laba6part2: laba6part2.c
		gcc laba6part2.c -o laba6part2 -ansi -Wall -pedantic
clean:
		rm laba6part1 laba6part2
