/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConfigManager */

#ifndef _Included_ConfigManager
#define _Included_ConfigManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConfigManager
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ConfigManager_create
  (JNIEnv *, jobject);

/*
 * Class:     ConfigManager
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ConfigManager_destroy
  (JNIEnv *, jobject);

/*
 * Class:     ConfigManager
 * Method:    manage
 * Signature: (Ljava/lang/String;BZ)V
 */
JNIEXPORT void JNICALL Java_ConfigManager_manage
  (JNIEnv *, jobject, jstring, jbyte, jboolean);

/*
 * Class:     ConfigManager
 * Method:    parseFrom
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_ConfigManager_parseFrom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ConfigManager
 * Method:    hasValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ConfigManager_hasValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ConfigManager
 * Method:    getStringValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ConfigManager_getStringValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ConfigManager
 * Method:    getIntValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ConfigManager_getIntValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ConfigManager
 * Method:    getFloatValue
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_ConfigManager_getFloatValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ConfigManager
 * Method:    getBooleanValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ConfigManager_getBooleanValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ConfigManager
 * Method:    getListValue
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ConfigManager_getListValue
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
