/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConfigManager_ParameterType */

#ifndef _Included_ConfigManager_ParameterType
#define _Included_ConfigManager_ParameterType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
